#  Copyright (c) 2021 Dell Inc. or its subsidiaries.
#  All Rights Reserved.

---
- name: Volume operations on PowerStore
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Get volume details using ID
      dellemc.powerstore.dellemc_powerstore_volume:
        array_ip: "{{array_ip}}"
        verifycert: False
        user: "{{user}}"
        password: "{{password}}"
        vol_name: "{{vol_name}}"
        state: "present"

